web:
  image: willseward/tcu-resources-web:1
  links:
    - mysql
mysql:
  image: willseward/tcu-resources-mysql:1
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_ONETIME_PASSWORD: "yes"
    MYSQL_USER: "${MYSQL_USER}"
    MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    MYSQL_DATABASE: "my-test-database"
  volumes:
    - "${MYSQL_VOLUME}:/var/lib/mysql"

